# version: '3.9'


services:
  backend: 
    image: aniket52kr/linkedin-clone-backend:latest
    container_name: linkedin-clone-backend
    restart: unless-stopped
    env_file:
      - ./Linkedin-clone-backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./Linkedin-clone-backend/uploads:/app/uploads
    networks:
      - linkedin-network


  frontend:
    image: aniket52kr/linkedin-clone-frontend:latest
    container_name: linkedin-clone-frontend
    restart: unless-stopped
    env_file:
      - ./Linkedin-clone-frontend/.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - linkedin-network

networks:
  linkedin-network:
    driver: bridge