# version: '3.8'

services:
  backend:
    image: aniket52kr/linkedin-clone-backend:latest
    container_name: linkedin-backend
    restart: unless-stopped
    env_file:
      - ./Linkedin-clone-backend/.env
    ports:
      - "3000:3000"
    networks:
      - linkedin-network
    

  frontend:
    image: aniket52kr/linkedin-clone-frontend:latest
    container_name: linkedin-frontend
    restart: unless-stopped
    env_file:
      - ./Linkedin-clone-frontend/.env
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - linkedin-network

networks:
  linkedin-network:
    driver: bridge